import re

with open('resources/views/admin/pengujian_aplikasi/detail.blade.php', 'r', encoding='utf-8') as f:
    content = f.read()

# Status Cards: Remove "Card Uji Keamanan VAPT"
content = re.sub(r'<!-- Card Uji Keamanan VAPT -->\s*<div class=\"bg-surface-container-lowest border border-amber-200 bg-amber-50/40 rounded-lg p-3 shadow-xs flex items-center justify-between\">\s*<div class=\"flex items-center gap-2\">\s*<div class=\"w-9 h-9 rounded-md bg-amber-100 text-amber-800 flex items-center justify-center\">\s*<span class=\"material-symbols-outlined text-title-md\" data-icon=\"pending_actions\">pending_actions</span>\s*</div>\s*<div>\s*<span class=\"block font-label-md text-label-md font-semibold text-on-surface\">Uji Keamanan Siber</span>\s*<span class=\"font-caption text-caption text-amber-800 font-medium\">Menunggu Dokumen BAST/VAPT CSIRT</span>\s*</div>\s*</div>\s*<span class=\"material-symbols-outlined text-amber-600\" data-icon=\"hourglass_top\">hourglass_top</span>\s*</div>', '', content)

# Change Upload grid from grid-cols-1 md:grid-cols-2 to grid-cols-1
content = content.replace('<div class="grid grid-cols-1 md:grid-cols-2 gap-6">', '<div class="grid grid-cols-1 gap-6">')

# Remove Area Unggah: Security & CSIRT Audit
content = re.sub(r'<!-- 2\. Area Unggah: Security & CSIRT Audit -->\s*<div class=\"flex flex-col space-y-2\">\s*<label class=\"font-label-lg text-label-lg font-semibold text-on-surface flex items-center justify-between\">\s*<span>2\. Berita Acara &amp; Pengujian Keamanan Aplikasi \(VAPT\)</span>\s*<span class=\"text-error font-medium text-caption\">\wajib</span>\s*</label>\s*<p class=\"font-caption text-caption text-on-surface-variant\">\s*Laporan Vulnerability Assessment &amp; Penetration Testing bertanda tangan pejabat CSIRT Riau\.\s*</p>\s*<!-- Dropzone Container -->\s*<div class=\"border-2 border-dashed border-outline-variant hover:border-primary rounded-lg p-6 flex flex-col items-center justify-center text-center bg-surface-container-low/40 hover:bg-surface-container-low transition-all duration-150 group cursor-pointer\">\s*<div class=\"w-12 h-12 rounded-full bg-secondary-container/30 flex items-center justify-center text-secondary group-hover:scale-105 transition-transform duration-150 mb-3 shadow-xs\">\s*<span class=\"material-symbols-outlined text-headline-sm\" data-icon=\"verified_user\">verified_user</span>\s*</div>\s*<p class=\"font-title-md text-title-md font-semibold text-on-surface mb-1\">\s*Tarik Berita Acara \(BAST\) Pengujian &amp; Hasil VAPT\s*</p>\s*<p class=\"font-body-sm text-body-sm text-on-surface-variant max-w-xs mb-4\">\s*atau klik untuk memilih berkas \(\.PDF bertandatangan pejabat berwenang CSIRT Riau\)\s*</p>\s*<button class=\"px-4 py-2 bg-surface-container-lowest border border-outline-variant text-primary font-label-lg text-label-lg rounded-md hover:bg-surface-container hover:border-primary transition-colors shadow-xs inline-flex items-center gap-1\.5\" type=\"button\">\s*<span class=\"material-symbols-outlined text-base\" data-icon=\"file_upload\">file_upload</span>\s*Pilih Berkas\s*</button>\s*<!-- Upload Pending State Banner -->\s*<div class=\"w-full mt-5 pt-4 border-t border-outline-variant/60 flex items-center justify-between text-left\">\s*<div class=\"flex items-center gap-2 min-w-0\">\s*<span class=\"material-symbols-outlined text-amber-600 text-lg\" data-icon=\"radio_button_unchecked\">radio_button_unchecked</span>\s*<div class=\"truncate\">\s*<span class=\"block font-label-md text-label-md font-medium text-on-surface-variant italic\">Belum ada berkas audit CSIRT yang dilampirkan</span>\s*<span class=\"block font-caption text-caption text-on-surface-variant\">Menunggu sertifikat kelaikan dari Subdit Sandi &amp; Siber</span>\s*</div>\s*</div>\s*<span class=\"px-2 py-0\.5 rounded text-\[10px\] font-semibold bg-amber-100 text-amber-800\">Menunggu</span>\s*</div>\s*</div>\s*</div>', '', content)

# Modify Checklist:
content = re.sub(r'<label class=\"flex items-start gap-2\.5 cursor-pointer\">\s*<input checked=\"\" class=\"rounded border-outline-variant text-primary focus:ring-secondary mt-0\.5 w-4 h-4\" type=\"checkbox\"/>\s*<span class=\"font-body-sm text-body-sm text-on-surface\">Enkripsi Data Sensitif AES-256 &amp; SSL A\+ aktif</span>\s*</label>\s*<label class=\"flex items-start gap-2\.5 cursor-pointer\">\s*<input checked=\"\" class=\"rounded border-outline-variant text-primary focus:ring-secondary mt-0\.5 w-4 h-4\" type=\"checkbox\"/>\s*<span class=\"font-body-sm text-body-sm text-on-surface\">Bebas temuan Critical/High Vulnerability \(CSIRT\)</span>\s*</label>', '', content)

# Change grid for Checklist:
content = content.replace('<div class="grid grid-cols-1 sm:grid-cols-3 gap-3">', '<div class="grid grid-cols-1 sm:grid-cols-1 gap-3">')

# Modify Log:
content = re.sub(r'<div class=\"py-2\.5 flex items-center justify-between text-body-sm\">\s*<div class=\"flex items-center gap-3\">\s*<span class=\"w-2 h-2 rounded-full bg-blue-500\"></span>\s*<span class=\"font-medium text-on-surface\">Pemindaian Kerentanan Otomatis \(DAST Scan\)</span>\s*<span class=\"text-caption text-on-surface-variant\">Server Sandbox Diskominfo</span>\s*</div>\s*<span class=\"font-caption text-caption text-on-surface-variant\">22 Nov 2025, 09:15 WIB</span>\s*</div>\s*<div class=\"py-2\.5 flex items-center justify-between text-body-sm\">\s*<div class=\"flex items-center gap-3\">\s*<span class=\"w-2 h-2 rounded-full bg-amber-500\"></span>\s*<span class=\"font-medium text-on-surface\">Penerbitan Tiket Remediasi Minor CSIRT</span>\s*<span class=\"text-caption text-on-surface-variant\">Mitigasi konfigurasi TLS &amp; Header HTTP</span>\s*</div>\s*<span class=\"font-caption text-caption text-on-surface-variant\">20 Nov 2025, 16:45 WIB</span>\s*</div>', '', content)

with open('resources/views/admin/pengujian_aplikasi/detail.blade.php', 'w', encoding='utf-8') as f:
    f.write(content)
